import sys
import xlsxwriter
import xlrd
import xlwt

def combine_all(file_name,sheet_all,index):
    #file to copy from
    wb = xlrd.open_workbook(file_name)
    sheet_srt = wb.sheet_by_index(0)
    len_srt = sheet_srt.nrows

    for i in range(len_srt):  # i stand for row in 'sheet_srt'
        line = sheet_srt.cell_value(i, 0)
        label = sheet_srt.cell_value(i, 1)
        sheet_all.write(i+index, 0, line)
        sheet_all.write(i+index, 1, label)
    return len_srt+index


# INPUT
workbook = xlsxwriter.Workbook(sys.argv[100]) #sheet to copy all to
worksheet = workbook.add_worksheet()

wb_write = xlwt.Workbook()
sheet_all = wb_write.add_sheet('all', cell_overwrite_ok=True)
index = 0
file_name = sys.argv[1]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[2]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[3]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[4]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[5]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[6]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[7]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[8]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[9]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[10]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[11]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[12]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[13]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[14]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[15]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[16]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[17]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[18]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[19]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[20]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[21]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[22]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[23]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[24]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[25]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[26]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[27]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[28]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[29]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[30]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[31]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[32]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[33]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[34]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[35]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[36]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[37]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[38]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[39]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[40]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[41]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[42]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[43]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[44]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[45]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[46]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[47]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[48]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[49]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[50]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[51]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[52]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[53]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[54]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[55]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[56]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[57]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[58]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[59]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[60]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[61]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[62]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[63]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[64]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[65]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[66]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[67]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[68]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[69]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[70]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[71]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[72]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[73]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[74]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[75]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[76]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[77]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[78]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[79]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[80]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[81]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[82]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[83]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[84]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[85]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[86]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[87]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[88]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[89]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[90]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[91]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[92]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[93]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[94]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[95]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[96]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[97]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[98]
index = combine_all(file_name,worksheet,index)
file_name = sys.argv[99]
index = combine_all(file_name,worksheet,index)

workbook.close()


